// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyafgLdgF-hjo-9rdPoj5ONtD3M9aMWnY',
    appId: '1:504291469947:web:ae70123d334fb139a110de',
    messagingSenderId: '504291469947',
    projectId: 'pkm-smart-ambulance',
    authDomain: 'pkm-smart-ambulance.firebaseapp.com',
    storageBucket: 'pkm-smart-ambulance.appspot.com',
    measurementId: 'G-48YJ8CQ22V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcfBvoZ-Cmw-KY4WfmbhM2MO4UEyRJja8',
    appId: '1:504291469947:android:87715421eb1dd322a110de',
    messagingSenderId: '504291469947',
    projectId: 'pkm-smart-ambulance',
    storageBucket: 'pkm-smart-ambulance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7JiSxg4agO5MeXTVvlN4sPz0BoQYKpEQ',
    appId: '1:504291469947:ios:be90563e1e58e290a110de',
    messagingSenderId: '504291469947',
    projectId: 'pkm-smart-ambulance',
    storageBucket: 'pkm-smart-ambulance.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7JiSxg4agO5MeXTVvlN4sPz0BoQYKpEQ',
    appId: '1:504291469947:ios:bf88a7bc539838f2a110de',
    messagingSenderId: '504291469947',
    projectId: 'pkm-smart-ambulance',
    storageBucket: 'pkm-smart-ambulance.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
